from dataclasses import dataclass

from app.domain.planning_conflicts.models import (
    PlanningConflictCategory,
    PlanningConflictSeverity,
)


@dataclass(frozen=True)
class PlanningConflictTemplate:
    category: PlanningConflictCategory
    severity: PlanningConflictSeverity
    title: str
    description: str
    action: str
    workspace: str
    rationale: str
    documentation_reference: str


_DOC = "PLANNING_WORKSPACE_CONTRACT_INVENTORY.md#planning-readiness"


PLANNING_CONFLICT_TEMPLATES = {
    "WORKFORCE_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.WORKFORCE,
        PlanningConflictSeverity.CRITICAL,
        "Workforce non disponibile",
        "Lo snapshot Workforce richiesto per la giornata non e disponibile.",
        "Apri Workforce e aggiorna i dati operativi della giornata.",
        "Workforce",
        "Il piano richiede risorse umane osservate nello stesso contesto.",
        _DOC,
    ),
    "FLEET_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.FLEET,
        PlanningConflictSeverity.CRITICAL,
        "Fleet non disponibile",
        "Lo snapshot Fleet richiesto per la giornata non e disponibile.",
        "Apri Fleet e aggiorna il parco mezzi operativo.",
        "Fleet",
        "Il piano richiede Asset osservati nello stesso contesto.",
        _DOC,
    ),
    "OPERATIONAL_UNIT_MISMATCH": PlanningConflictTemplate(
        PlanningConflictCategory.OPERATIONAL_UNIT,
        PlanningConflictSeverity.CRITICAL,
        "Operational Unit non allineata",
        "Gli input non descrivono la stessa Operational Unit.",
        "Seleziona la stessa Operational Unit in Workforce e Fleet, poi aggiorna gli input.",
        "Planning Workspace",
        "Input con scope diversi non possono comporre lo stesso piano.",
        _DOC,
    ),
    "PLANNING_DATE_MISMATCH": PlanningConflictTemplate(
        PlanningConflictCategory.OPERATIONAL_UNIT,
        PlanningConflictSeverity.CRITICAL,
        "Data operativa non allineata",
        "Workforce e Fleet non si riferiscono alla stessa data operativa.",
        "Aggiorna Workforce e Fleet per la data selezionata nel Planning Workspace.",
        "Planning Workspace",
        "Il piano puo usare soltanto input riferiti alla stessa giornata.",
        _DOC,
    ),
    "SNAPSHOT_INVALID": PlanningConflictTemplate(
        PlanningConflictCategory.VALIDATION,
        PlanningConflictSeverity.CRITICAL,
        "Snapshot non valido",
        "Uno snapshot contiene dati che non superano la validazione Core.",
        "Correggi il dato indicato nel workspace sorgente e aggiorna lo snapshot.",
        "Source Workspace",
        "Un input non valido non puo sostenere la conferma del piano.",
        _DOC,
    ),
    "WORKFORCE_SNAPSHOT_STALE": PlanningConflictTemplate(
        PlanningConflictCategory.FRESHNESS,
        PlanningConflictSeverity.HIGH,
        "Workforce non aggiornato",
        "Lo snapshot Workforce ha superato la finestra di freshness.",
        "Apri Workforce e aggiorna le disponibilita prima della conferma.",
        "Workforce",
        "Disponibilita non aggiornate non sono affidabili per il piano.",
        _DOC,
    ),
    "FLEET_SNAPSHOT_STALE": PlanningConflictTemplate(
        PlanningConflictCategory.FRESHNESS,
        PlanningConflictSeverity.HIGH,
        "Fleet non aggiornato",
        "Lo snapshot Fleet ha superato la finestra di freshness.",
        "Apri Fleet e aggiorna disponibilita e stato dei mezzi.",
        "Fleet",
        "Lo stato non aggiornato degli Asset non e affidabile per il piano.",
        _DOC,
    ),
    "SNAPSHOT_EXPIRING_SOON": PlanningConflictTemplate(
        PlanningConflictCategory.FRESHNESS,
        PlanningConflictSeverity.LOW,
        "Snapshot vicino alla scadenza",
        "La finestra di freshness residua e inferiore alla soglia prevista.",
        "Aggiorna il workspace sorgente prima di confermare il piano.",
        "Source Workspace",
        "Un aggiornamento ora evita di confermare dati prossimi alla scadenza.",
        _DOC,
    ),
    "WORKFORCE_CAPABILITIES_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.CAPABILITY,
        PlanningConflictSeverity.MEDIUM,
        "Capability Workforce incomplete",
        "Le capability delle Human Resource non sono disponibili o complete.",
        "Completa le capability delle persone nel Workspace Workforce.",
        "Workforce",
        "Le capability sono necessarie per verificare i vincoli delle future assegnazioni.",
        _DOC,
    ),
    "FLEET_CAPABILITIES_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.CAPABILITY,
        PlanningConflictSeverity.MEDIUM,
        "Capability Fleet incomplete",
        "Le capability degli Asset non sono disponibili o complete.",
        "Completa le capability dei mezzi nel Workspace Fleet.",
        "Fleet",
        "Le capability descrivono i vincoli operativi degli Asset.",
        _DOC,
    ),
    "ZERO_WORKFORCE_AVAILABLE": PlanningConflictTemplate(
        PlanningConflictCategory.WORKFORCE,
        PlanningConflictSeverity.CRITICAL,
        "Nessuna persona disponibile",
        "Lo snapshot Workforce non contiene Human Resource disponibili.",
        "Verifica assenze, turni e disponibilita nel Workspace Workforce.",
        "Workforce",
        "Non e possibile preparare un piano senza risorse disponibili.",
        _DOC,
    ),
    "ZERO_FLEET_AVAILABLE": PlanningConflictTemplate(
        PlanningConflictCategory.FLEET,
        PlanningConflictSeverity.CRITICAL,
        "Nessun mezzo disponibile",
        "Lo snapshot Fleet non contiene Asset disponibili.",
        "Verifica disponibilita e officina nel Workspace Fleet.",
        "Fleet",
        "Non e possibile preparare un piano senza Asset disponibili.",
        _DOC,
    ),
    "VERSION_MISMATCH": PlanningConflictTemplate(
        PlanningConflictCategory.VERSION,
        PlanningConflictSeverity.CRITICAL,
        "Versioni input non compatibili",
        "Le versioni dei contratti Planning Input non sono allineate.",
        "Aggiorna entrambe le sorgenti e rigenera il Planning Input.",
        "Planning Workspace",
        "La composizione richiede contratti compatibili e verificabili.",
        _DOC,
    ),
    "FINGERPRINT_MISMATCH": PlanningConflictTemplate(
        PlanningConflictCategory.VERSION,
        PlanningConflictSeverity.CRITICAL,
        "Fingerprint input non valido",
        "Il fingerprint di uno o piu Planning Input non corrisponde al contenuto.",
        "Rigenera il Planning Input dalle sorgenti correnti.",
        "Planning Workspace",
        "Il fingerprint garantisce che il contenuto non sia cambiato dopo la produzione.",
        _DOC,
    ),
    "RUNTIME_INCOMPATIBLE": PlanningConflictTemplate(
        PlanningConflictCategory.RUNTIME,
        PlanningConflictSeverity.CRITICAL,
        "Runtime non compatibile",
        "Il Runtime non puo comporre gli input nel contesto richiesto.",
        "Risolvi i conflitti di scope e integrita indicati, poi riprova.",
        "Planning Workspace",
        "Il Runtime deve produrre una composizione coerente prima della conferma.",
        _DOC,
    ),
    "ENVELOPE_INCOMPLETE": PlanningConflictTemplate(
        PlanningConflictCategory.RUNTIME,
        PlanningConflictSeverity.CRITICAL,
        "Planning Input Envelope incompleto",
        "Il Runtime non ha prodotto un envelope completo e validato.",
        "Completa Workforce e Fleet, quindi rigenera il Planning Input.",
        "Planning Workspace",
        "L'envelope e il contratto unitario richiesto dal Planning Workspace.",
        _DOC,
    ),
    "DEPENDENCY_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.DEPENDENCY,
        PlanningConflictSeverity.CRITICAL,
        "Dipendenza obbligatoria mancante",
        "Una dipendenza dichiarata dal Planning Input non e disponibile.",
        "Ripristina la dipendenza indicata nel workspace sorgente e aggiorna lo snapshot.",
        "Source Workspace",
        "Le dipendenze obbligatorie non possono essere ignorate.",
        _DOC,
    ),
    "OPTIONAL_DEPENDENCY_MISSING": PlanningConflictTemplate(
        PlanningConflictCategory.DEPENDENCY,
        PlanningConflictSeverity.LOW,
        "Dipendenza opzionale mancante",
        "Una dipendenza opzionale dichiarata non e disponibile.",
        "Verifica la dipendenza nel workspace sorgente prima della conferma.",
        "Source Workspace",
        "La dipendenza non blocca il piano ma richiede una verifica consapevole.",
        _DOC,
    ),
    "SNAPSHOT_PARTIAL": PlanningConflictTemplate(
        PlanningConflictCategory.VALIDATION,
        PlanningConflictSeverity.MEDIUM,
        "Snapshot parziale",
        "Lo snapshot non contiene tutti i dati operativi previsti.",
        "Completa i dati indicati nel workspace sorgente e aggiorna lo snapshot.",
        "Source Workspace",
        "I dati parziali riducono l'affidabilita della valutazione.",
        _DOC,
    ),
    "WORKFORCE_COVERAGE_REDUCED": PlanningConflictTemplate(
        PlanningConflictCategory.WORKFORCE,
        PlanningConflictSeverity.HIGH,
        "Copertura Workforce ridotta",
        "Le persone disponibili sono inferiori al fabbisogno osservato.",
        "Verifica assenze e copertura nel Workspace Workforce.",
        "Workforce",
        "La copertura insufficiente puo impedire l'esecuzione del piano.",
        _DOC,
    ),
    "LEGACY_CONTRACT": PlanningConflictTemplate(
        PlanningConflictCategory.LEGACY,
        PlanningConflictSeverity.INFO,
        "Contratto legacy osservato",
        "Un segnale esplicito proviene dal flusso Planning legacy.",
        "Consulta il flusso legacy senza modificare il piano dal Conflict Review.",
        "Operations",
        "Il flusso legacy resta compatibile durante la migrazione progressiva.",
        _DOC,
    ),
}
