from enum import Enum


class ConflictSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class ConflictCode(str, Enum):
    UNKNOWN_DRIVER = "UNKNOWN_DRIVER"
    UNKNOWN_VEHICLE = "UNKNOWN_VEHICLE"
    VEHICLE_MULTI_DRIVER = "VEHICLE_MULTI_DRIVER"
    DRIVER_MULTI_ROUTE = "DRIVER_MULTI_ROUTE"
    UNAVAILABLE_VEHICLE_ASSIGNED = "UNAVAILABLE_VEHICLE_ASSIGNED"
    DRIVER_WITHOUT_VEHICLE = "DRIVER_WITHOUT_VEHICLE"
    ROUTE_WITHOUT_DRIVER = "ROUTE_WITHOUT_DRIVER"
    INVALID_VEHICLE_PLATE = "INVALID_VEHICLE_PLATE"
    DUPLICATE_ROW = "DUPLICATE_ROW"
    UNKNOWN_STATION = "UNKNOWN_STATION"
    INSUFFICIENT_OPERATIONAL_VEHICLES = "INSUFFICIENT_OPERATIONAL_VEHICLES"
    LOW_RESERVE_MARGIN = "LOW_RESERVE_MARGIN"
